AllCops:
  Include:
    - Rakefile
  Exclude:
    - lib/cocoapods-core/vendor/**
    - spec/fixtures/**

# https://github.com/bbatsov/rubocop/issues/946
NonNilCheck:
  Enabled: false

# https://github.com/bbatsov/rubocop/issues/947
Documentation:
  Enabled: false

# Remove once the support for Ruby 1.8.7 has been phased out
HashSyntax:
  EnforcedStyle: hash_rockets

# fail vs raise https://github.com/bbatsov/ruby-style-guide/issues/233
SignalException:
  EnforcedStyle: only_raise

# Warns about having a new line before the comment of the first method.
EmptyLinesAroundBody:
  Enabled: false

# The indentation is preferred to show branching.
IfUnlessModifier:
  Enabled: false

# This can be changes as soon as rubocop can automatically fix it
TrailingComma:
  EnforcedStyleForMultiline: comma

Encoding:
  Enabled: false

AssignmentInCondition:
  Enabled: false

# Warns about class methods.
TrivialAccessors:
  Enabled: false

# Do not want!
AsciiComments:
  Enabled: false

#------------------------------------------------------------------------------

BracesAroundHashParameters:
  Exclude:
    - lib/**/dsl.rb

FileName:
  Exclude:
    - lib/cocoapods-core.rb

#------------------------------------------------------------------------------
# Needs fixing
#------------------------------------------------------------------------------

CyclomaticComplexity:
  Max: 6
  Max: 11

ClassLength:
  Max: 100
  Max: 280

MethodLength:
  Max: 10
  Max: 27

LineLength:
  Max: 80
  Max: 120

RescueException:
  Enabled: false

