steps:
  - label: ":hammer: Specs"
    agents:
      m1: true
    commands:
      - echo "--- Initialize git"
      - git submodule update --init
      - ./.github/scripts/setup_test_repo.sh
      - echo "--- Bundler"
      - gem install bundler:1.17.3
      - bundle config path vendor/bundle
      - bundle install --jobs 4 --retry 3 --without debugging documentation
      - echo "+++ Run Specs"
      - bundle exec rake spec
