source 'http://source.cocoapods.com/specs'
source 'http://source2.cocoapods.com/specs'
platform :ios
pod 'SSZipArchive',      '>= 1'
pod 'ASIHTTPRequest',    '~> 1.8.0'
pod 'Reachability'                  # part of ASIHTTPRequest
pod 'ASIWebPageRequest',        '< 1.8.2'  # part of ASIHTTPRequest
